# Generated by Django 6.0.1 on 2026-02-16 20:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 5),
                            ("about_section", 12),
                            ("founder", 20),
                            ("stats", 24),
                            ("gallery_import", 27),
                            ("eco", 30),
                            ("news", 34),
                            ("contacts_section", 36),
                        ],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья", "required": False},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                        ("button_text", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "О производителе"},
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            9: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            10: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            11: (
                                "wagtail.blocks.StreamBlock",
                                [[("image", 9), ("video", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("text", 7),
                                        ("link", 8),
                                        ("gallery", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            14: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Должность", "required": False},
                            ),
                            16: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Цитата", "required": False},
                            ),
                            17: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "История предприятия", "required": False},
                            ),
                            19: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("founder_image", 13),
                                        ("founder_name", 14),
                                        ("founder_role", 15),
                                        ("quote", 16),
                                        ("button_text", 14),
                                        ("button_url", 17),
                                        ("history_title", 18),
                                        ("history_text", 19),
                                        ("history_bg_image", 13),
                                    ]
                                ],
                                {},
                            ),
                            21: ("wagtail.blocks.CharBlock", (), {}),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 21), ("unit", 14), ("description", 21)]],
                                {},
                            ),
                            23: ("wagtail.blocks.ListBlock", (22,), {}),
                            24: ("wagtail.blocks.StructBlock", [[("stats", 23)]], {}),
                            25: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Страница галереи",
                                    "page_type": ["gallery.GalleryPage"],
                                },
                            ),
                            26: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 3, "label": "Количество элементов"},
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("gallery_page", 25), ("count", 26)]],
                                {
                                    "label": "Вставка Галереи",
                                    "template": "about/blocks/gallery_import_wrapper.html",
                                },
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            29: ("wagtail.blocks.TextBlock", (), {}),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 9),
                                        ("icon", 9),
                                        ("title", 28),
                                        ("text", 29),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Новости"},
                            ),
                            32: ("wagtail.blocks.IntegerBlock", (), {"default": 3}),
                            33: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "page_type": ["news.NewsIndexPage"],
                                    "required": False,
                                },
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 31),
                                        ("subtitle", 3),
                                        ("count", 32),
                                        ("news_index_page", 33),
                                    ]
                                ],
                                {},
                            ),
                            35: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 35)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DeliveryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 5),
                            ("intro", 9),
                            ("tabs_section", 28),
                            ("stats", 33),
                            ("eco", 37),
                            ("contacts_section", 39),
                        ],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья", "required": False},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                        ("button_text", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Заголовок (слева)"},
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                    ],
                                    "label": "Текст (правая часть, колонка 1)",
                                },
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                    ],
                                    "label": "Текст (правая часть, колонка 2)",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("column_1", 7), ("column_2", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Название таба (напр. Оплата заказа)"},
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Картинка"),
                                        ("font", "Иконочный шрифт"),
                                    ],
                                    "label": "Тип иконки таба",
                                },
                            ),
                            12: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Иконка таба (картинка)", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Используйте классы из шрифта 'nut'",
                                    "label": "Класс иконки таба (например: icons-credit-card)",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок контента (напр. Способы оплаты)",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Картинка"),
                                        ("font", "Иконочный шрифт"),
                                    ],
                                    "label": "Тип иконки",
                                },
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Иконка (картинка)", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Используйте классы из шрифта 'nut'. Например: icons-vector12, icons-credit-card и т.д.",
                                    "label": "Класс иконки (например: icons-vector12)",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Название пункта"},
                            ),
                            19: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Описание", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 15),
                                        ("icon_image", 16),
                                        ("icon_font_class", 17),
                                        ("title", 18),
                                        ("description", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Простой текстовый абзац без иконки",
                                    "label": "Текстовый абзац",
                                },
                            ),
                            22: (
                                "wagtail.blocks.StreamBlock",
                                [[("icon_item", 20), ("text_paragraph", 21)]],
                                {
                                    "label": "Содержимое (иконки + текст или просто текст)",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Например: 'Написать нам'",
                                    "label": "Текст кнопки",
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Например: /contacts/ или https://example.com",
                                    "label": "URL кнопки",
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Картинка справа"},
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("tab_label", 10),
                                        ("tab_icon_type", 11),
                                        ("tab_icon_image", 12),
                                        ("tab_icon_font_class", 13),
                                        ("content_title", 14),
                                        ("content_items", 22),
                                        ("button_text", 23),
                                        ("button_url", 24),
                                        ("image", 25),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.ListBlock",
                                (26,),
                                {"label": "Список табов"},
                            ),
                            28: ("wagtail.blocks.StructBlock", [[("tabs", 27)]], {}),
                            29: ("wagtail.blocks.CharBlock", (), {}),
                            30: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 29), ("unit", 30), ("description", 29)]],
                                {},
                            ),
                            32: ("wagtail.blocks.ListBlock", (31,), {}),
                            33: ("wagtail.blocks.StructBlock", [[("stats", 32)]], {}),
                            34: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            35: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            36: ("wagtail.blocks.TextBlock", (), {}),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 34),
                                        ("icon", 34),
                                        ("title", 35),
                                        ("text", 36),
                                    ]
                                ],
                                {},
                            ),
                            38: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 38)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="WholesalePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 5),
                            ("intro", 9),
                            ("tabs_section", 28),
                            ("stats", 33),
                            ("eco", 37),
                            ("contacts_section", 39),
                        ],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья", "required": False},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                        ("button_text", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Заголовок (слева)"},
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                    ],
                                    "label": "Текст (правая часть, колонка 1)",
                                },
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                    ],
                                    "label": "Текст (правая часть, колонка 2)",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("column_1", 7), ("column_2", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Название таба (напр. Оплата заказа)"},
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Картинка"),
                                        ("font", "Иконочный шрифт"),
                                    ],
                                    "label": "Тип иконки таба",
                                },
                            ),
                            12: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Иконка таба (картинка)", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Используйте классы из шрифта 'nut'",
                                    "label": "Класс иконки таба (например: icons-credit-card)",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Заголовок контента (напр. Способы оплаты)",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Картинка"),
                                        ("font", "Иконочный шрифт"),
                                    ],
                                    "label": "Тип иконки",
                                },
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Иконка (картинка)", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Используйте классы из шрифта 'nut'. Например: icons-vector12, icons-credit-card и т.д.",
                                    "label": "Класс иконки (например: icons-vector12)",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Название пункта"},
                            ),
                            19: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Описание", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 15),
                                        ("icon_image", 16),
                                        ("icon_font_class", 17),
                                        ("title", 18),
                                        ("description", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Простой текстовый абзац без иконки",
                                    "label": "Текстовый абзац",
                                },
                            ),
                            22: (
                                "wagtail.blocks.StreamBlock",
                                [[("icon_item", 20), ("text_paragraph", 21)]],
                                {
                                    "label": "Содержимое (иконки + текст или просто текст)",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Например: 'Написать нам'",
                                    "label": "Текст кнопки",
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Например: /contacts/ или https://example.com",
                                    "label": "URL кнопки",
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Картинка справа"},
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("tab_label", 10),
                                        ("tab_icon_type", 11),
                                        ("tab_icon_image", 12),
                                        ("tab_icon_font_class", 13),
                                        ("content_title", 14),
                                        ("content_items", 22),
                                        ("button_text", 23),
                                        ("button_url", 24),
                                        ("image", 25),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.ListBlock",
                                (26,),
                                {"label": "Список табов"},
                            ),
                            28: ("wagtail.blocks.StructBlock", [[("tabs", 27)]], {}),
                            29: ("wagtail.blocks.CharBlock", (), {}),
                            30: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 29), ("unit", 30), ("description", 29)]],
                                {},
                            ),
                            32: ("wagtail.blocks.ListBlock", (31,), {}),
                            33: ("wagtail.blocks.StructBlock", [[("stats", 32)]], {}),
                            34: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            35: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            36: ("wagtail.blocks.TextBlock", (), {}),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 34),
                                        ("icon", 34),
                                        ("title", 35),
                                        ("text", 36),
                                    ]
                                ],
                                {},
                            ),
                            38: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 38)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
