# Generated by Django 6.0.1 on 2026-02-20 11:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"verbose_name": "О компании", "verbose_name_plural": "О компании"},
        ),
        migrations.AlterModelOptions(
            name="deliverypage",
            options={
                "verbose_name": "Оплата и доставка",
                "verbose_name_plural": "Оплата и доставка",
            },
        ),
        migrations.AlterModelOptions(
            name="wholesalepage",
            options={
                "verbose_name": "Опт и корпоративные клиенты",
                "verbose_name_plural": "Опт и корпоративные клиенты",
            },
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("about_section", 12),
                    ("founder", 22),
                    ("stats", 28),
                    ("gallery_import", 31),
                    ("contacts_section", 33),
                ],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "О производителе", "label": "Заголовок"},
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                            ],
                            "label": "Текст",
                        },
                    ),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Ссылка на страницу", "required": False},
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение"},
                    ),
                    10: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео"},
                    ),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 9), ("video", 10)]],
                        {"label": "Галерея (Слайдер)"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("text", 7), ("link", 8), ("gallery", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение основателя", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Имя основателя", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Должность", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Цитата", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Текст кнопки", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Ссылка кнопки", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "История предприятия",
                            "label": "Заголовок истории",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Текст истории", "required": False},
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение истории", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("founder_image", 13),
                                ("founder_name", 14),
                                ("founder_role", 15),
                                ("quote", 16),
                                ("button_text", 17),
                                ("button_url", 18),
                                ("history_title", 19),
                                ("history_text", 20),
                                ("history_bg_image", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "Значение (цифра)"}),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Единица измерения", "required": False},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 23), ("unit", 24), ("description", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.ListBlock",
                        (26,),
                        {"label": "Список статистики"},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("stats", 27)]], {}),
                    29: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Страница галереи",
                            "page_type": ["gallery.GalleryPage"],
                        },
                    ),
                    30: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 3, "label": "Количество элементов"},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("gallery_page", 29), ("count", 30)]],
                        {
                            "label": "Импорт галереи",
                            "template": "about/blocks/gallery_import_wrapper.html",
                        },
                    ),
                    32: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("contact_page", 32)]], {}),
                },
                verbose_name="Контент страницы",
            ),
        ),
        migrations.AlterField(
            model_name="deliverypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("intro", 9),
                    ("tabs_section", 28),
                    ("stats", 34),
                    ("eco", 39),
                    ("contacts_section", 41),
                ],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок (слева)"}),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                            ],
                            "label": "Текст (правая часть, колонка 1)",
                        },
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                            ],
                            "label": "Текст (правая часть, колонка 2)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("column_1", 7), ("column_2", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: 'Безналичный расчет'",
                            "label": "Название таба (в меню)",
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Картинка"),
                                ("font", "Иконочный шрифт"),
                            ],
                            "label": "Тип иконки таба",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка таба (Картинка)", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: icons-card",
                            "label": "Класс иконки таба",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: Оплата банковскими картами (Без переплат)",
                            "label": "Главный заголовок контента",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Картинка"),
                                ("font", "Иконочный шрифт"),
                            ],
                            "label": "Тип иконки",
                        },
                    ),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка (Картинка)", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: icons-delivery",
                            "label": "Класс иконки (Шрифт)",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    19: ("wagtail.blocks.TextBlock", (), {"label": "Описание"}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 15),
                                ("icon_image", 16),
                                ("icon_font_class", 17),
                                ("title", 18),
                                ("description", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Простой текстовый абзац без иконки",
                            "label": "Текстовый абзац",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [[("icon_item", 20), ("text_paragraph", 21)]],
                        {
                            "label": "Содержимое (иконки + текст или просто текст)",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: 'Написать нам'",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Например: /contacts/ или https://example.com",
                            "label": "URL кнопки",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Картинка справа"},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tab_label", 10),
                                ("tab_icon_type", 11),
                                ("tab_icon_image", 12),
                                ("tab_icon_font_class", 13),
                                ("title", 14),
                                ("content_items", 22),
                                ("button_text", 23),
                                ("button_url", 24),
                                ("image", 25),
                            ]
                        ],
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"label": "Список табов"}),
                    28: ("wagtail.blocks.StructBlock", [[("tabs", 27)]], {}),
                    29: ("wagtail.blocks.CharBlock", (), {"label": "Значение (цифра)"}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Единица измерения", "required": False},
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 29), ("unit", 30), ("description", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ListBlock",
                        (32,),
                        {"label": "Список статистики"},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("stats", 33)]], {}),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    36: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    38: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 35),
                                ("icon", 36),
                                ("title", 37),
                                ("text", 38),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("contact_page", 40)]], {}),
                },
                verbose_name="Контент страницы",
            ),
        ),
        migrations.AlterField(
            model_name="wholesalepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("intro", 9),
                    ("tabs_section", 28),
                    ("stats", 34),
                    ("eco", 39),
                    ("contacts_section", 41),
                ],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок (слева)"}),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                            ],
                            "label": "Текст (правая часть, колонка 1)",
                        },
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                            ],
                            "label": "Текст (правая часть, колонка 2)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("column_1", 7), ("column_2", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: 'Безналичный расчет'",
                            "label": "Название таба (в меню)",
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Картинка"),
                                ("font", "Иконочный шрифт"),
                            ],
                            "label": "Тип иконки таба",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка таба (Картинка)", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: icons-card",
                            "label": "Класс иконки таба",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: Оплата банковскими картами (Без переплат)",
                            "label": "Главный заголовок контента",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Картинка"),
                                ("font", "Иконочный шрифт"),
                            ],
                            "label": "Тип иконки",
                        },
                    ),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка (Картинка)", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: icons-delivery",
                            "label": "Класс иконки (Шрифт)",
                            "required": False,
                        },
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    19: ("wagtail.blocks.TextBlock", (), {"label": "Описание"}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 15),
                                ("icon_image", 16),
                                ("icon_font_class", 17),
                                ("title", 18),
                                ("description", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Простой текстовый абзац без иконки",
                            "label": "Текстовый абзац",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [[("icon_item", 20), ("text_paragraph", 21)]],
                        {
                            "label": "Содержимое (иконки + текст или просто текст)",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: 'Написать нам'",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Например: /contacts/ или https://example.com",
                            "label": "URL кнопки",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Картинка справа"},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tab_label", 10),
                                ("tab_icon_type", 11),
                                ("tab_icon_image", 12),
                                ("tab_icon_font_class", 13),
                                ("title", 14),
                                ("content_items", 22),
                                ("button_text", 23),
                                ("button_url", 24),
                                ("image", 25),
                            ]
                        ],
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"label": "Список табов"}),
                    28: ("wagtail.blocks.StructBlock", [[("tabs", 27)]], {}),
                    29: ("wagtail.blocks.CharBlock", (), {"label": "Значение (цифра)"}),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Единица измерения", "required": False},
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 29), ("unit", 30), ("description", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ListBlock",
                        (32,),
                        {"label": "Список статистики"},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("stats", 33)]], {}),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    36: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    38: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 35),
                                ("icon", 36),
                                ("title", 37),
                                ("text", 38),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    41: ("wagtail.blocks.StructBlock", [[("contact_page", 40)]], {}),
                },
                verbose_name="Контент страницы",
            ),
        ),
    ]
