# Generated by Django 6.0.1 on 2026-02-16 20:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("hero", 5), ("detailed_contacts", 23), ("text_content", 24)],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья", "required": False},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                        ("button_text", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Contacts",
                                    "label": "Main Title",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Image"),
                                        ("font", "Font Icon"),
                                    ],
                                    "label": "Icon Type",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Icon (Image)", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Example: icons-phone, icons-post, icons-home",
                                    "label": "Icon Class",
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Phone Number", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (10,),
                                {"label": "Phone List", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Link", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 7),
                                        ("icon_image", 8),
                                        ("icon_font_class", 9),
                                        ("link", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.ListBlock",
                                (13,),
                                {
                                    "label": "Social Buttons (WhatsApp, Telegram)",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 7),
                                        ("icon_image", 8),
                                        ("icon_font_class", 9),
                                        ("phones", 11),
                                        ("socials", 14),
                                    ]
                                ],
                                {"label": "Phones & Socials Block", "required": False},
                            ),
                            16: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {"label": "Email", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 7),
                                        ("icon_image", 8),
                                        ("icon_font_class", 9),
                                        ("email", 16),
                                    ]
                                ],
                                {"label": "Email Block", "required": False},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title (e.g. Office)", "required": False},
                            ),
                            19: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Address Text",
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 7),
                                        ("icon_image", 8),
                                        ("icon_font_class", 9),
                                        ("title", 18),
                                        ("text", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.ListBlock",
                                (20,),
                                {"label": "Address List", "required": False},
                            ),
                            22: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "label": "Map Embed Code (Google Maps iframe)",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("main_title", 6),
                                        ("phone_section", 15),
                                        ("email_section", 17),
                                        ("addresses", 21),
                                        ("map_embed", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                    ],
                                    "label": "Text Content",
                                },
                            ),
                        },
                        verbose_name="Contact Page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
