# Generated by Django 6.0.1 on 2026-02-20 11:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactpage",
            options={
                "verbose_name": "Contact Page",
                "verbose_name_plural": "Contact Pages",
            },
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5), ("detailed_contacts", 24), ("text_content", 25)],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {"label": "Hero Block"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Contacts",
                            "label": "Main Title",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("image", "Image"), ("font", "Font Icon")],
                            "label": "Icon Type",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Icon (Image)", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Example: icons-phone, icons-post, icons-home",
                            "label": "Icon Class",
                            "required": False,
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Phone Number"}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"label": "Phone List", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("link", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {"label": "Social Networks", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("phones", 11),
                                ("socials", 14),
                            ]
                        ],
                        {"label": "Phones & Socials Block", "required": False},
                    ),
                    16: ("wagtail.blocks.EmailBlock", (), {"label": "Email Address"}),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Email List", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("emails", 17),
                            ]
                        ],
                        {"label": "Email Block", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Branch/Title", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "br"],
                            "label": "Address Text",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("text", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"label": "Address List", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "label": "Map Embed Code (Google Maps iframe)",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("main_title", 6),
                                ("phone_section", 15),
                                ("email_section", 18),
                                ("addresses", 22),
                                ("map_embed", 23),
                            ]
                        ],
                        {"label": "Detailed Contacts"},
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ul",
                                "ol",
                            ],
                            "label": "Text Content",
                        },
                    ),
                },
                verbose_name="Contact Page Content",
            ),
        ),
    ]
