# Generated by Django 6.0.1 on 2026-02-20 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contactpage_options_alter_contactpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactpage",
            options={
                "verbose_name": "Страница контактов",
                "verbose_name_plural": "Страница контактов",
            },
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5), ("detailed_contacts", 24), ("text_content", 25)],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {"label": "Блок героя"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Контакты",
                            "label": "Основное название",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Изображение"),
                                ("font", "Шрифт Иконка"),
                            ],
                            "label": "Тип значка",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка (изображение)", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Пример: icons-phone, icons-post, icons-home",
                            "label": "Класс Icon",
                            "required": False,
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Номер телефона"}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"label": "Список телефонов", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Ссылка", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("link", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {"label": "Социальные сети", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("phones", 11),
                                ("socials", 14),
                            ]
                        ],
                        {"label": "Телефоны и социальные сети", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"label": "Адрес электронной почты"},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {
                            "label": "Список адресов электронной почты",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("emails", 17),
                            ]
                        ],
                        {"label": "Блокировка электронной почты", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Филиал/Название", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "br"],
                            "label": "Текст адреса",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("text", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"label": "Список адресов", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "label": "Код для вставки карты (iframe Google Maps)",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("main_title", 6),
                                ("phone_section", 15),
                                ("email_section", 18),
                                ("addresses", 22),
                                ("map_embed", 23),
                            ]
                        ],
                        {"label": "Подробные контакты"},
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ul",
                                "ol",
                            ],
                            "label": "Текстовое содержание",
                        },
                    ),
                },
                verbose_name="Содержание страницы Контакты",
            ),
        ),
    ]
