# Generated by Django 6.0.1 on 2026-02-16 20:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 5),
                            ("gallery_section", 21),
                            ("contacts_section", 23),
                        ],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья", "required": False},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                        ("button_text", 4),
                                    ]
                                ],
                                {"group": "Main"},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Наша галерея",
                                    "label": "Заголовок секции",
                                },
                            ),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Описание секции", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 6,
                                    "help_text": "Сколько карточек показывать за раз. Работает только на детальной странице галереи.",
                                    "label": "Элементов на странице (для пагинации)",
                                },
                            ),
                            9: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео (приоритет)", "required": False},
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Картинка", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Заголовок", "required": False},
                            ),
                            12: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Подзаголовок", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("col-12", "100%"),
                                        ("col-lg-6", "50%"),
                                        ("col-lg-4", "33%"),
                                    ],
                                    "label": "Размер",
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 9),
                                        ("image", 10),
                                        ("title", 11),
                                        ("subtitle", 12),
                                        ("size", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Фоновая картинка"},
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Иконка", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Текст", "required": False},
                            ),
                            18: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("col-lg-4", "33%"),
                                        ("col-lg-6", "50%"),
                                        ("col-lg-3", "25%"),
                                    ],
                                    "label": "Размер",
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 15),
                                        ("icon", 16),
                                        ("title", 11),
                                        ("description", 17),
                                        ("size", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.StreamBlock",
                                [[("gallery_hero", 14), ("gallery_card", 19)]],
                                {"label": "Элементы галереи"},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 7),
                                        ("items_per_page", 8),
                                        ("items", 20),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 22)]],
                                {"group": "Main"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
