# Generated by Django 6.0.1 on 2026-02-20 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_gallerypage_options_alter_gallerypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerypage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5), ("gallery_section", 20), ("contacts_section", 22)],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {"group": "Основное"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Наша галерея", "label": "Заголовок секции"},
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Описание секции", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 6,
                            "help_text": "Сколько карточек показывать за раз. Работает только на детальной странице галереи.",
                            "label": "Элементов на странице (для пагинации)",
                        },
                    ),
                    9: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео (приоритет)", "required": False},
                    ),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Картинка", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Заголовок", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("col-12", "100%"),
                                ("col-lg-6", "50%"),
                                ("col-lg-4", "33%"),
                            ],
                            "label": "Размер",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 9),
                                ("image", 10),
                                ("title", 11),
                                ("subtitle", 3),
                                ("size", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновая картинка"},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Текст", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("col-lg-4", "33%"),
                                ("col-lg-6", "50%"),
                                ("col-lg-3", "25%"),
                            ],
                            "label": "Размер",
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 14),
                                ("icon", 15),
                                ("title", 11),
                                ("description", 16),
                                ("size", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("gallery_hero", 13), ("gallery_card", 18)]],
                        {"label": "Элементы галереи"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 6),
                                ("description", 7),
                                ("items_per_page", 8),
                                ("items", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("contact_page", 21)]],
                        {"group": "Основное"},
                    ),
                },
                verbose_name="Контент страницы",
            ),
        ),
    ]
