# Generated by Django 6.0.1 on 2026-02-16 20:09

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPackaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Упаковка")),
            ],
            options={
                "verbose_name": "Упаковка",
                "verbose_name_plural": "Справочник: Упаковки",
            },
        ),
        migrations.CreateModel(
            name="ProductTaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Вкус")),
            ],
            options={
                "verbose_name": "Вкус",
                "verbose_name_plural": "Справочник: Вкусы",
            },
        ),
        migrations.CreateModel(
            name="ShopIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок H1"
                    ),
                ),
                (
                    "intro",
                    models.TextField(blank=True, verbose_name="Описание раздела"),
                ),
                (
                    "footer_blocks",
                    wagtail.fields.StreamField(
                        [("eco", 3), ("contacts_section", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 0),
                                        ("icon", 0),
                                        ("title", 1),
                                        ("text", 2),
                                    ]
                                ],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Часть ссылки, например: greckiy-oreh",
                        unique=True,
                        verbose_name="URL (slug)",
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, verbose_name="Артикул"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "weight",
                    models.CharField(default="40г.", max_length=50, verbose_name="Вес"),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Краткое описание"),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Полное описание"
                    ),
                ),
                (
                    "energy_value",
                    models.CharField(
                        blank=True,
                        default="654 Ккал.",
                        max_length=255,
                        verbose_name="Энерг. ценность",
                    ),
                ),
                (
                    "shelf_life",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Срок годности"
                    ),
                ),
                ("composition", models.TextField(blank=True, verbose_name="Состав")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_sale", models.BooleanField(default=False, verbose_name="Акция")),
                (
                    "live",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Главное фото",
                    ),
                ),
                (
                    "packaging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.productpackaging",
                        verbose_name="Упаковка",
                    ),
                ),
                (
                    "tastes",
                    models.ManyToManyField(
                        blank=True, to="shop.producttaste", verbose_name="Вкусы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
    ]
