# Generated by Django 6.0.1 on 2026-02-16 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopindexpage",
            name="custom_title",
        ),
        migrations.RemoveField(
            model_name="shopindexpage",
            name="intro",
        ),
    ]
