# Generated by Django 6.0.1 on 2026-02-17 08:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_shopindexpage_custom_title_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopindexpage",
            name="custom_title",
            field=models.CharField(
                blank=True,
                help_text="Если не заполнено, используется обычный title",
                max_length=255,
                verbose_name="Заголовок для Hero",
            ),
        ),
        migrations.AddField(
            model_name="shopindexpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Hero изображение",
            ),
        ),
        migrations.CreateModel(
            name="ProductGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "product",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение галереи",
                "verbose_name_plural": "Изображения галереи",
                "ordering": ["sort_order"],
            },
        ),
    ]
