# Generated by Django 6.0.1 on 2026-02-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_shopindexpage_custom_title_shopindexpage_hero_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: 40г, 100г, 200г",
                        max_length=50,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        help_text="Для сортировки", verbose_name="Значение в граммах"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вес",
                "verbose_name_plural": "Справочник: Вес",
                "ordering": ["value"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.AddField(
            model_name="product",
            name="weight_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.productweight",
                verbose_name="Вес",
            ),
        ),
    ]
