# Generated by Django 6.0.1 on 2026-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_productweight_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgalleryimage",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="0 = первая/главная, 10 = вторая, 20 = третья и т.д.",
                verbose_name="Позиция (0 = главная)",
            ),
        ),
    ]
