# Generated by Django 6.0.1 on 2026-02-17 17:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_productgalleryimage_position"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True, verbose_name="Кастомное описание (перекрывает базу)"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("image", 1)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст"}),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Изображение"},
                            ),
                        },
                        verbose_name="Дополнительные блоки",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page",
                        to="shop.product",
                        verbose_name="Товар из базы данных",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
