# Generated by Django 6.0.1 on 2026-02-17 18:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_productpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpage",
            name="content_blocks",
            field=wagtail.fields.StreamField(
                [
                    ("sku_block", 1),
                    ("attribute_block", 4),
                    ("icon_text_block", 8),
                    ("price_block", 10),
                    ("rich_text", 11),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Артикул", "label": "Текст (например: Артикул)"},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("label", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: Состав",
                            "label": "Название характеристики",
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("composition", "Состав"),
                                ("weight", "Вес (строка)"),
                                ("energy_value", "Энергетическая ценность"),
                                ("shelf_life", "Срок годности"),
                                ("packaging", "Упаковка"),
                            ],
                            "label": "Что вывести из базы?",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 2), ("attribute_type", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Картинка иконки", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: nut-icon icons-truck",
                            "label": "CSS класс иконки (если нет картинки)",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_image", 5), ("icon_class", 6), ("text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Цена", "label": "Текст (например: Ваша цена)"},
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("label", 9)]], {}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"label": "Просто текст"}),
                },
                verbose_name="Конструктор правой колонки",
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("image", 1), ("tabs_section", 20)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст"}),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Название таба (напр. Оплата заказа)"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Картинка"),
                                ("font", "Иконочный шрифт"),
                            ],
                            "label": "Тип иконки таба",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка таба (картинка)", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Используйте классы из шрифта 'nut'",
                            "label": "Класс иконки таба (например: icons-credit-card)",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Заголовок контента (напр. Способы оплаты)",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Картинка"),
                                ("font", "Иконочный шрифт"),
                            ],
                            "label": "Тип иконки",
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка (картинка)", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Используйте классы из шрифта 'nut'. Например: icons-vector12, icons-credit-card и т.д.",
                            "label": "Класс иконки (например: icons-vector12)",
                            "required": False,
                        },
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Название пункта"}),
                    11: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Описание", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 7),
                                ("icon_image", 8),
                                ("icon_font_class", 9),
                                ("title", 10),
                                ("description", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Простой текстовый абзац без иконки",
                            "label": "Текстовый абзац",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [[("icon_item", 12), ("text_paragraph", 13)]],
                        {
                            "label": "Содержимое (иконки + текст или просто текст)",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: 'Написать нам'",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Например: /contacts/ или https://example.com",
                            "label": "URL кнопки",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Картинка справа"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tab_label", 2),
                                ("tab_icon_type", 3),
                                ("tab_icon_image", 4),
                                ("tab_icon_font_class", 5),
                                ("content_title", 6),
                                ("content_items", 14),
                                ("button_text", 15),
                                ("button_url", 16),
                                ("image", 17),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"label": "Список табов"}),
                    20: ("wagtail.blocks.StructBlock", [[("tabs", 19)]], {}),
                },
                verbose_name="Дополнительные блоки",
            ),
        ),
    ]
