# Generated by Django 6.0.1 on 2026-02-17 19:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_productpage_content_blocks_alter_productpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgalleryimage",
            options={
                "ordering": ["position"],
                "verbose_name": "Изображение галереи",
                "verbose_name_plural": "Изображения галереи",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.AlterField(
            model_name="productpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("tabs_section", 6), ("contacts_section", 8), ("rich_text", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Заголовок таба", "required": True},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Картинка слева"),
                                ("right", "Картинка справа"),
                            ],
                            "label": "Расположение картинки",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("image", 1),
                                ("image_alignment", 2),
                                ("content", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {"label": "Список табов"}),
                    6: ("wagtail.blocks.StructBlock", [[("tabs", 5)]], {}),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    8: ("wagtail.blocks.StructBlock", [[("contact_page", 7)]], {}),
                },
                verbose_name="Основной контент (снизу)",
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="content_blocks",
            field=wagtail.fields.StreamField(
                [
                    ("sku_block", 1),
                    ("attribute_block", 4),
                    ("icon_text_block", 8),
                    ("price_block", 10),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Артикул", "label": "Текст (например: Артикул)"},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("label", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: Состав",
                            "label": "Название характеристики",
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("composition", "Состав"),
                                ("weight", "Вес (строка)"),
                                ("energy_value", "Энергетическая ценность"),
                                ("shelf_life", "Срок годности"),
                                ("packaging", "Упаковка"),
                            ],
                            "label": "Что вывести из базы?",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 2), ("attribute_type", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Картинка иконки", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Например: nut-icon icons-truck",
                            "label": "CSS класс иконки (если нет картинки)",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_image", 5), ("icon_class", 6), ("text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Цена", "label": "Текст (например: Ваша цена)"},
                    ),
                    10: ("wagtail.blocks.StructBlock", [[("label", 9)]], {}),
                },
                verbose_name="Конструктор правой колонки",
            ),
        ),
    ]
