# Generated by Django 6.0.1 on 2026-02-17 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_productgalleryimage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
