# Generated by Django 6.0.1 on 2026-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_remove_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="composition_en",
            field=models.TextField(blank=True, null=True, verbose_name="Состав"),
        ),
        migrations.AddField(
            model_name="product",
            name="composition_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Состав"),
        ),
        migrations.AddField(
            model_name="product",
            name="composition_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Состав"),
        ),
        migrations.AddField(
            model_name="product",
            name="energy_value_en",
            field=models.CharField(
                blank=True,
                default="654 Ккал.",
                max_length=255,
                null=True,
                verbose_name="Энерг. ценность",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="energy_value_ru",
            field=models.CharField(
                blank=True,
                default="654 Ккал.",
                max_length=255,
                null=True,
                verbose_name="Энерг. ценность",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="energy_value_uk",
            field=models.CharField(
                blank=True,
                default="654 Ккал.",
                max_length=255,
                null=True,
                verbose_name="Энерг. ценность",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Срок годности"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Срок годности"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_uk",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Срок годности"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название товара"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название товара"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uk",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название товара"
            ),
        ),
    ]
