# Generated by Django 6.0.1 on 2026-02-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_product_composition_en_product_composition_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pages",
                to="shop.product",
                verbose_name="Товар из базы данных",
            ),
        ),
    ]
