# Generated by Django 6.0.1 on 2026-02-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_productpage_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug_en",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Часть ссылки, например: greckiy-oreh",
                null=True,
                unique=True,
                verbose_name="URL (slug)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_ru",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Часть ссылки, например: greckiy-oreh",
                null=True,
                unique=True,
                verbose_name="URL (slug)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug_uk",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Часть ссылки, например: greckiy-oreh",
                null=True,
                unique=True,
                verbose_name="URL (slug)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Часть ссылки, например: greckiy-oreh",
                unique=True,
                verbose_name="URL (slug)",
            ),
        ),
    ]
