# Generated by Django 6.0.1 on 2026-02-18 16:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_product_slug_en_product_slug_ru_product_slug_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Орех Причерноморья", "required": False},
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Смотреть видео", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Контент страницы (сверху)",
            ),
        ),
    ]
