# Generated by Django 6.0.1 on 2026-02-18 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_shopindexpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopindexpage",
            name="custom_title",
        ),
        migrations.RemoveField(
            model_name="shopindexpage",
            name="hero_image",
        ),
    ]
