# Generated by Django 6.0.1 on 2026-02-19 14:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_remove_shopindexpage_custom_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpage",
            name="content_blocks",
        ),
        migrations.RemoveField(
            model_name="productpage",
            name="custom_description",
        ),
        migrations.RemoveField(
            model_name="productpage",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="storage_conditions",
            field=models.TextField(
                blank=True,
                default="Хранить в помещениях, защищенных от попадания прямых солнечных лучей, при температуре от +3 °C до +20 °C, и относительной влажности воздуха не более 75 %",
                verbose_name="Условия хранения",
            ),
        ),
        migrations.AddField(
            model_name="productpage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("contacts_section", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("contact_page", 0)]], {}),
                },
                verbose_name="Подвал (контакты)",
            ),
        ),
        migrations.AddField(
            model_name="shopindexpage",
            name="global_product_tabs",
            field=wagtail.fields.StreamField(
                [("tabs_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Заголовок таба", "required": True},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Картинка слева"),
                                ("right", "Картинка справа"),
                            ],
                            "label": "Расположение картинки",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("image", 1),
                                ("image_alignment", 2),
                                ("content", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {"label": "Список табов"}),
                    6: ("wagtail.blocks.StructBlock", [[("tabs", 5)]], {}),
                },
                verbose_name="Общие табы для страниц товаров",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimage",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="0 = первая/главная, 10 = вторая и т.д.",
                verbose_name="Позиция (0 = главная)",
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("tabs_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Заголовок таба", "required": True},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Картинка слева"),
                                ("right", "Картинка справа"),
                            ],
                            "label": "Расположение картинки",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("image", 1),
                                ("image_alignment", 2),
                                ("content", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {"label": "Список табов"}),
                    6: ("wagtail.blocks.StructBlock", [[("tabs", 5)]], {}),
                },
                verbose_name="Общие табы для всех товаров",
            ),
        ),
    ]
