# Generated by Django 6.0.1 on 2026-02-19 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_remove_productpage_content_blocks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopindexpage",
            name="global_product_tabs",
        ),
    ]
