# Generated by Django 6.0.1 on 2026-02-20 11:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_remove_shopindexpage_global_product_tabs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="storage_conditions",
            field=models.TextField(
                blank=True,
                default="Хранить в помещениях при...",
                verbose_name="Условия хранения",
            ),
        ),
        migrations.AlterField(
            model_name="shopindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Контент страницы (сверху)",
            ),
        ),
        migrations.AlterField(
            model_name="shopindexpage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("eco", 4), ("contacts_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("icon", 1),
                                ("title", 2),
                                ("text", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("contact_page", 5)]], {}),
                },
            ),
        ),
    ]
