# Generated by Django 6.0.1 on 2026-02-20 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_alter_product_storage_conditions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgalleryimage",
            options={
                "verbose_name": "Изображение галереи",
                "verbose_name_plural": "Изображения галереи",
            },
        ),
        migrations.RemoveField(
            model_name="productgalleryimage",
            name="position",
        ),
        migrations.AlterField(
            model_name="productpage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("contacts_section", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("contact_page", 0)]], {}),
                },
                verbose_name="Подвал (контакты)",
            ),
        ),
        migrations.AlterField(
            model_name="shopindexpage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("eco", 4), ("contacts_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("icon", 1),
                                ("title", 2),
                                ("text", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("contact_page", 5)]], {}),
                },
            ),
        ),
    ]
