# Generated by Django 6.0.1 on 2026-02-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_alter_productgalleryimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgalleryimage",
            name="sort_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
