# Generated by Django 6.0.1 on 2026-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_alter_productgalleryimage_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgalleryimage",
            name="caption",
        ),
        migrations.AlterField(
            model_name="productgalleryimage",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
