# Generated by Django 6.0.1 on 2026-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_cartpage_checkoutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartpage",
            name="manager_phone",
            field=models.CharField(
                default="+38 067 777 14 12",
                max_length=50,
                verbose_name="Телефон менеджера",
            ),
        ),
        migrations.AddField(
            model_name="cartpage",
            name="manager_title",
            field=models.CharField(
                default="Ваш личный менеджер Олег",
                max_length=255,
                verbose_name="Текст 'Личный менеджер'",
            ),
        ),
    ]
