# Generated by Django 6.0.1 on 2026-02-22 12:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_cartpage_manager_phone_cartpage_manager_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersuccesspage",
            name="background_image",
        ),
        migrations.AddField(
            model_name="ordersuccesspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Баннер (Hero)",
            ),
        ),
        migrations.AlterField(
            model_name="ordersuccesspage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("contacts_section", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("contact_page", 0)]], {}),
                },
            ),
        ),
    ]
