# Generated by Django 6.0.1 on 2026-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_remove_ordersuccesspage_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopindexpage",
            name="products_per_page",
            field=models.PositiveIntegerField(
                default=9,
                help_text="Укажите, сколько товаров показывать изначально и при нажатии 'Показать еще'",
                verbose_name="Товаров на страницу",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("nova_poshta", "Новая почта (по Украине оплата за счет Клиента)"),
                    ("courier", "Курьер по Одессе"),
                    ("pickup", "Самовывоз со склада"),
                ],
                default="nova_poshta",
                max_length=20,
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("invoice", "Безналичный расчет"),
                    ("card", "LiqPay / Приват24"),
                    ("cash", "Наличными при получении (Наложенным платежом)"),
                ],
                default="card",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
