# Generated by Django 6.0.1 on 2026-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpackaging",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productpackaging",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productpackaging",
            name="name_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="producttaste",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Вкус"),
        ),
        migrations.AddField(
            model_name="producttaste",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Вкус"),
        ),
        migrations.AddField(
            model_name="producttaste",
            name="name_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Вкус"),
        ),
        migrations.AddField(
            model_name="productweight",
            name="name_en",
            field=models.CharField(
                help_text="Например: 40г, 100г, 200г",
                max_length=50,
                null=True,
                verbose_name="Вес",
            ),
        ),
        migrations.AddField(
            model_name="productweight",
            name="name_ru",
            field=models.CharField(
                help_text="Например: 40г, 100г, 200г",
                max_length=50,
                null=True,
                verbose_name="Вес",
            ),
        ),
        migrations.AddField(
            model_name="productweight",
            name="name_uk",
            field=models.CharField(
                help_text="Например: 40г, 100г, 200г",
                max_length=50,
                null=True,
                verbose_name="Вес",
            ),
        ),
    ]
