# Generated by Django 6.0.1 on 2026-02-04 15:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 4),
                            ("products", 9),
                            ("about", 15),
                            ("stats", 20),
                            ("mission", 23),
                            ("benefits", 26),
                            ("eco", 28),
                            ("news", 32),
                            ("contacts", 36),
                        ],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья"},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Продукция"},
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["shop.ProductPage"]},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"label": "Выберите товары"},
                            ),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 5),
                                        ("description", 3),
                                        ("featured_products", 7),
                                        ("shop_link", 8),
                                    ]
                                ],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "О производителе"},
                            ),
                            11: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            12: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            13: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            14: (
                                "wagtail.blocks.StreamBlock",
                                [[("image", 12), ("video", 13)]],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 10),
                                        ("text", 11),
                                        ("link", 8),
                                        ("gallery", 14),
                                    ]
                                ],
                                {},
                            ),
                            16: ("wagtail.blocks.CharBlock", (), {}),
                            17: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 16), ("unit", 17), ("description", 16)]],
                                {},
                            ),
                            19: ("wagtail.blocks.ListBlock", (18,), {}),
                            20: ("wagtail.blocks.StructBlock", [[("stats", 19)]], {}),
                            21: ("wagtail.blocks.TextBlock", (), {}),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео"},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 13),
                                        ("overlay_text", 21),
                                        ("button_text", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 12),
                                        ("icon", 12),
                                        ("title", 16),
                                        ("description", 21),
                                    ]
                                ],
                                {},
                            ),
                            25: ("wagtail.blocks.ListBlock", (24,), {}),
                            26: ("wagtail.blocks.StructBlock", [[("cards", 25)]], {}),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 12),
                                        ("icon", 12),
                                        ("title", 27),
                                        ("text", 21),
                                    ]
                                ],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Новости"},
                            ),
                            30: ("wagtail.blocks.IntegerBlock", (), {"default": 3}),
                            31: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["news.NewsIndexPage"]},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 29),
                                        ("subtitle", 3),
                                        ("count", 30),
                                        ("news_index_page", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: ("wagtail.blocks.ListBlock", (16,), {}),
                            34: ("wagtail.blocks.EmailBlock", (), {}),
                            35: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("phones", 33),
                                        ("email", 34),
                                        ("address_office", 21),
                                        ("address_production", 21),
                                        ("map_embed_code", 35),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
