# Generated by Django 6.0.1 on 2026-02-16 20:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 5),
                            ("about", 12),
                            ("stats", 17),
                            ("benefits", 21),
                            ("eco", 23),
                            ("news", 27),
                            ("contacts_section", 29),
                        ],
                        block_lookup={
                            0: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Видео", "required": False},
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "label": "Фоновая картинка (если нет видео)",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Орех Причерноморья", "required": False},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Смотреть видео", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("video", 0),
                                        ("image", 1),
                                        ("title", 2),
                                        ("subtitle", 3),
                                        ("button_text", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "О производителе"},
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                    ]
                                },
                            ),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            9: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            10: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            11: (
                                "wagtail.blocks.StreamBlock",
                                [[("image", 9), ("video", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("text", 7),
                                        ("link", 8),
                                        ("gallery", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: ("wagtail.blocks.CharBlock", (), {}),
                            14: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 13), ("unit", 14), ("description", 13)]],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: ("wagtail.blocks.StructBlock", [[("stats", 16)]], {}),
                            18: ("wagtail.blocks.TextBlock", (), {}),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 9),
                                        ("icon", 9),
                                        ("title", 13),
                                        ("description", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: ("wagtail.blocks.ListBlock", (19,), {}),
                            21: ("wagtail.blocks.StructBlock", [[("cards", 20)]], {}),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 9),
                                        ("icon", 9),
                                        ("title", 22),
                                        ("text", 18),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Новости"},
                            ),
                            25: ("wagtail.blocks.IntegerBlock", (), {"default": 3}),
                            26: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "page_type": ["news.NewsIndexPage"],
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 24),
                                        ("subtitle", 3),
                                        ("count", 25),
                                        ("news_index_page", 26),
                                    ]
                                ],
                                {},
                            ),
                            28: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 28)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
