# Generated by Django 6.0.1 on 2026-02-23 10:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("about", 12),
                    ("featured_products", 16),
                    ("stats", 22),
                    ("benefits", 31),
                    ("eco", 36),
                    ("news", 40),
                    ("contacts_section", 42),
                ],
                block_lookup={
                    0: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "label": "Фоновая картинка (если нет видео)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Орех Причерноморья",
                            "label": "Заголовок",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Смотреть видео",
                            "label": "Текст кнопки",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 0),
                                ("image", 1),
                                ("title", 2),
                                ("subtitle", 3),
                                ("button_text", 4),
                            ]
                        ],
                        {"label": "Главный экран (Hero)"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "О производителе", "label": "Заголовок"},
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                            ],
                            "label": "Текст",
                        },
                    ),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Ссылка на страницу", "required": False},
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение"},
                    ),
                    10: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео"},
                    ),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 9), ("video", 10)]],
                        {"label": "Галерея (Слайдер)"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("text", 7), ("link", 8), ("gallery", 11)]],
                        {"label": "Блок 'О производителе'"},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Продукция", "label": "Заголовок"},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Описание", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 3, "label": "Количество товаров"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("description", 14), ("count", 15)]],
                        {"label": "Блок продуктов"},
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"label": "Значение (цифра)"}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Единица измерения", "required": False},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 17), ("unit", 18), ("description", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {"label": "Список статистики"},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("stats", 21)]],
                        {"label": "Блок статистики"},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Заголовок блока", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Описание блока", "required": False},
                    ),
                    25: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение"},
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка"},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    28: ("wagtail.blocks.TextBlock", (), {"label": "Описание"}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 25),
                                ("icon", 26),
                                ("title", 27),
                                ("description", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {"label": "Карточки преимуществ"},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("description", 24), ("cards", 30)]],
                        {"label": "Блок преимуществ"},
                    ),
                    32: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    33: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    35: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 32),
                                ("icon", 33),
                                ("title", 34),
                                ("text", 35),
                            ]
                        ],
                        {"label": "Эко баннер"},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Новости", "label": "Заголовок"},
                    ),
                    38: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 3, "label": "Количество новостей"},
                    ),
                    39: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Страница новостей (для кнопки 'Все новости')",
                            "page_type": ["news.NewsIndexPage"],
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 37),
                                ("subtitle", 3),
                                ("count", 38),
                                ("news_index_page", 39),
                            ]
                        ],
                        {"label": "Последние новости"},
                    ),
                    41: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("contact_page", 41)]],
                        {"label": "Блок контактов"},
                    ),
                },
                verbose_name="Контент страницы",
            ),
        ),
    ]
