# Generated by Django 6.0.1 on 2026-02-16 20:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
        ("wagtailmedia", "0005_alter_media_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="H1 Title"
                    ),
                ),
                (
                    "intro",
                    models.TextField(blank=True, verbose_name="Section Description"),
                ),
                (
                    "news_per_page",
                    models.IntegerField(default=6, verbose_name="News per page"),
                ),
                (
                    "recent_news_count",
                    models.IntegerField(
                        default=3, verbose_name="Sidebar recent news count"
                    ),
                ),
                (
                    "sidebar_widget",
                    wagtail.fields.StreamField(
                        [("social_widget", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Join Us", "label": "Title"},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Image"),
                                        ("font", "Font Icon"),
                                    ],
                                    "label": "Icon Type",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Icon (Image)", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Example: icons-phone, icons-post, icons-home",
                                    "label": "Icon Class",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Link", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_type", 2),
                                        ("icon_image", 3),
                                        ("icon_font_class", 4),
                                        ("link", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"label": "Social Networks"},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("socials", 7)]],
                                {},
                            ),
                        },
                        verbose_name="Sidebar Social Widget",
                    ),
                ),
                (
                    "footer_blocks",
                    wagtail.fields.StreamField(
                        [("eco", 3), ("contacts_section", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 0),
                                        ("icon", 0),
                                        ("title", 1),
                                        ("text", 2),
                                    ]
                                ],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Publication Date")),
                (
                    "is_wide_display",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the news item will occupy the full width (col-12) in the list.",
                        verbose_name="Full Width (Wide)?",
                    ),
                ),
                (
                    "show_text_on_preview",
                    models.BooleanField(
                        default=False,
                        help_text="If checked: Title and Intro will be centered over the image/video (white text). If unchecked: below the image (black text).",
                        verbose_name="Show Title/Intro over Preview?",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="For the news list",
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("media_block", 4), ("eco_banner", 8)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "label": "Text Block",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image", "required": False},
                            ),
                            2: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"label": "Video", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                    ],
                                    "help_text": "This text will be displayed over the image or video.",
                                    "label": "Text over media",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("video", 2), ("overlay_text", 3)]],
                                {"label": "Media (Photo/Video) + Text"},
                            ),
                            5: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Эко продукция"},
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 5),
                                        ("icon", 5),
                                        ("title", 6),
                                        ("text", 7),
                                    ]
                                ],
                                {"label": "Eco Banner"},
                            ),
                        },
                        verbose_name="Content Constructor",
                    ),
                ),
                (
                    "preview_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview: Image",
                    ),
                ),
                (
                    "preview_video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailmedia.media",
                        verbose_name="Preview: Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Page",
                "ordering": ["-date"],
            },
            bases=("wagtailcore.page",),
        ),
    ]
