# Generated by Django 6.0.1 on 2026-02-20 11:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsindexpage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("eco", 4), ("contacts_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("icon", 1),
                                ("title", 2),
                                ("text", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Choose Contact Page",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("contact_page", 5)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("media_block", 4), ("eco_banner", 9)],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "label": "Text Block",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    2: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Video", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "h4", "bold", "italic", "link"],
                            "help_text": "This text will be displayed over the image or video.",
                            "label": "Text over media",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("video", 2), ("overlay_text", 3)]],
                        {"label": "Media (Photo/Video) + Text"},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 5),
                                ("icon", 6),
                                ("title", 7),
                                ("text", 8),
                            ]
                        ],
                        {"label": "Eco Banner"},
                    ),
                },
                verbose_name="Content Constructor",
            ),
        ),
    ]
