# Generated by Django 6.0.1 on 2026-02-20 20:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_newsindexpage_footer_blocks_and_more"),
        ("wagtailimages", "0027_image_description"),
        ("wagtailmedia", "0005_alter_media_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspage",
            options={"ordering": ["-date"], "verbose_name": "Страница новостей"},
        ),
        migrations.AlterField(
            model_name="newsindexpage",
            name="custom_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="H1 Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="newsindexpage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("eco", 4), ("contacts_section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("icon", 1),
                                ("title", 2),
                                ("text", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("contact_page", 5)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="newsindexpage",
            name="intro",
            field=models.TextField(blank=True, verbose_name="Описание раздела"),
        ),
        migrations.AlterField(
            model_name="newsindexpage",
            name="news_per_page",
            field=models.IntegerField(default=6, verbose_name="Новости на странице"),
        ),
        migrations.AlterField(
            model_name="newsindexpage",
            name="recent_news_count",
            field=models.IntegerField(
                default=3, verbose_name="Количество последних новостей в боковой панели"
            ),
        ),
        migrations.AlterField(
            model_name="newsindexpage",
            name="sidebar_widget",
            field=wagtail.fields.StreamField(
                [("social_widget", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Присоединяйтесь к нам", "label": "Название"},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Подзаголовок", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Изображение"),
                                ("font", "Шрифт Иконка"),
                            ],
                            "label": "Тип значка",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка (изображение)", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Пример: icons-phone, icons-post, icons-home",
                            "label": "Класс Icon",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Ссылка", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_type", 2),
                                ("icon_image", 3),
                                ("icon_font_class", 4),
                                ("link", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {"label": "Социальные сети"}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("socials", 7)]],
                        {},
                    ),
                },
                verbose_name="Социальный виджет боковой панели",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("media_block", 4), ("eco_banner", 9)],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "label": "Текстовый блок",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Изображение", "required": False},
                    ),
                    2: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {"label": "Видео", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "h4", "bold", "italic", "link"],
                            "help_text": "Этот текст будет отображаться поверх изображения или видео.",
                            "label": "Текст над медиа",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("video", 2), ("overlay_text", 3)]],
                        {"label": "Медиа (фото/видео) + текст"},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Фоновое изображение", "required": False},
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Иконка", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Эко продукция", "label": "Заголовок"},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Текст"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 5),
                                ("icon", 6),
                                ("title", 7),
                                ("text", 8),
                            ]
                        ],
                        {"label": "Эко-баннер"},
                    ),
                },
                verbose_name="Конструктор контента",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="date",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="Для списка новостей",
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="is_wide_display",
            field=models.BooleanField(
                default=False,
                help_text="Если этот флажок установлен, новость будет занимать всю ширину (col-12) в списке.",
                verbose_name="Полная ширина (широкий)?",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="preview_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Предварительный просмотр: Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="preview_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailmedia.media",
                verbose_name="Предварительный просмотр: Видео",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="show_text_on_preview",
            field=models.BooleanField(
                default=False,
                help_text="Если флажок установлен: заголовок и введение будут выровнены по центру над изображением/видео (белый текст). Если флажок не установлен: под изображением (черный текст).",
                verbose_name="Показать название/вступление над превью?",
            ),
        ),
    ]
