# Generated by Django 6.0.1 on 2026-02-16 20:10

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "promo_text",
                    models.CharField(
                        blank=True, default="Орех Причерноморья", max_length=255
                    ),
                ),
                (
                    "footer_blocks",
                    wagtail.fields.StreamField(
                        [("contacts_section", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Choose Contact Page",
                                    "page_type": ["contacts.ContactPage"],
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.StructBlock",
                                [[("contact_page", 0)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
    ]
