# Generated by Django 6.0.1 on 2026-02-20 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profilepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("contacts_section", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("contact_page", 0)]], {}),
                },
            ),
        ),
    ]
