# Generated by Django 6.0.1 on 2026-02-23 11:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profilepage_footer_blocks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilepage",
            name="promo_image",
        ),
        migrations.RemoveField(
            model_name="profilepage",
            name="promo_text",
        ),
        migrations.AddField(
            model_name="profilepage",
            name="manager_phone",
            field=models.CharField(
                default="+38 067 777 14 12",
                max_length=50,
                verbose_name="Телефон менеджера",
            ),
        ),
        migrations.AddField(
            model_name="profilepage",
            name="manager_title",
            field=models.CharField(
                default="Ваш личный менеджер Олег",
                max_length=255,
                verbose_name="Текст 'Личный менеджер'",
            ),
        ),
        migrations.AlterField(
            model_name="profilepage",
            name="footer_blocks",
            field=wagtail.fields.StreamField(
                [("contacts_section", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Выберите страницу Контакты",
                            "page_type": ["contacts.ContactPage"],
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("contact_page", 0)]], {}),
                },
                verbose_name="Блок контактов",
            ),
        ),
    ]
