# Generated by Django 6.0.1 on 2026-02-19 13:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_text",
                    models.CharField(
                        default="Ваша персональная скидка - 5%",
                        max_length=255,
                        verbose_name="Текст скидки",
                    ),
                ),
                (
                    "logo_text",
                    models.CharField(
                        default="ОРЕХ<br> ПРИЧЕРНОМОРЬЯ",
                        help_text="Разрешен тег <br> для переноса строки",
                        max_length=255,
                        verbose_name="Текст возле логотипа",
                    ),
                ),
                (
                    "phone_1_code",
                    models.CharField(
                        default="+38 (044)",
                        max_length=20,
                        verbose_name="Код телефона 1",
                    ),
                ),
                (
                    "phone_1_number",
                    models.CharField(
                        default="750-50-11",
                        max_length=20,
                        verbose_name="Номер телефона 1",
                    ),
                ),
                (
                    "phone_2_code",
                    models.CharField(
                        default="+38 (097)",
                        max_length=20,
                        verbose_name="Код телефона 2",
                    ),
                ),
                (
                    "phone_2_number",
                    models.CharField(
                        default="775-50-51",
                        max_length=20,
                        verbose_name="Номер телефона 2",
                    ),
                ),
                (
                    "call_text",
                    models.CharField(
                        default="Ждем Вашего звонка<br> ежедневно с 9 до 18",
                        max_length=255,
                        verbose_name="Текст возле кнопки",
                    ),
                ),
                (
                    "developer_text",
                    models.TextField(
                        default='Разработано <a href="#" class="dev"><span>AVADA</span> MEDIA</a>',
                        verbose_name="Текст разработчика",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="Copyright © 2019. Все права защищены",
                        max_length=255,
                        verbose_name="Копирайт",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Логотип сайта",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("viber", "Viber"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=50,
                        verbose_name="Платформа/Иконка",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("social", "Социальная сеть (Вверху слева и в подвале)"),
                            ("messenger", "Мессенджер (Возле номеров телефонов)"),
                        ],
                        default="social",
                        max_length=20,
                        verbose_name="Расположение",
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "setting",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="core.sitesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
