# Generated by Django 6.0.1 on 2026-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="call_text_en",
            field=models.CharField(
                default="Ждем Вашего звонка<br> ежедневно с 9 до 18",
                max_length=255,
                null=True,
                verbose_name="Текст возле кнопки",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="call_text_ru",
            field=models.CharField(
                default="Ждем Вашего звонка<br> ежедневно с 9 до 18",
                max_length=255,
                null=True,
                verbose_name="Текст возле кнопки",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="call_text_uk",
            field=models.CharField(
                default="Ждем Вашего звонка<br> ежедневно с 9 до 18",
                max_length=255,
                null=True,
                verbose_name="Текст возле кнопки",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="copyright_text_en",
            field=models.CharField(
                default="Copyright © 2019. Все права защищены",
                max_length=255,
                null=True,
                verbose_name="Копирайт",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="copyright_text_ru",
            field=models.CharField(
                default="Copyright © 2019. Все права защищены",
                max_length=255,
                null=True,
                verbose_name="Копирайт",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="copyright_text_uk",
            field=models.CharField(
                default="Copyright © 2019. Все права защищены",
                max_length=255,
                null=True,
                verbose_name="Копирайт",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_text_en",
            field=models.TextField(
                default='Разработано <a href="#" class="dev"><span>AVADA</span> MEDIA</a>',
                null=True,
                verbose_name="Текст разработчика",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_text_ru",
            field=models.TextField(
                default='Разработано <a href="#" class="dev"><span>AVADA</span> MEDIA</a>',
                null=True,
                verbose_name="Текст разработчика",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="developer_text_uk",
            field=models.TextField(
                default='Разработано <a href="#" class="dev"><span>AVADA</span> MEDIA</a>',
                null=True,
                verbose_name="Текст разработчика",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="discount_text_en",
            field=models.CharField(
                default="Ваша персональная скидка - 5%",
                max_length=255,
                null=True,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="discount_text_ru",
            field=models.CharField(
                default="Ваша персональная скидка - 5%",
                max_length=255,
                null=True,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="discount_text_uk",
            field=models.CharField(
                default="Ваша персональная скидка - 5%",
                max_length=255,
                null=True,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_text_en",
            field=models.CharField(
                default="ОРЕХ<br> ПРИЧЕРНОМОРЬЯ",
                help_text="Разрешен тег <br> для переноса строки",
                max_length=255,
                null=True,
                verbose_name="Текст возле логотипа",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_text_ru",
            field=models.CharField(
                default="ОРЕХ<br> ПРИЧЕРНОМОРЬЯ",
                help_text="Разрешен тег <br> для переноса строки",
                max_length=255,
                null=True,
                verbose_name="Текст возле логотипа",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_text_uk",
            field=models.CharField(
                default="ОРЕХ<br> ПРИЧЕРНОМОРЬЯ",
                help_text="Разрешен тег <br> для переноса строки",
                max_length=255,
                null=True,
                verbose_name="Текст возле логотипа",
            ),
        ),
    ]
