# Generated by Django 6.0.1 on 2026-02-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_sitesettings_call_text_en_sitesettings_call_text_ru_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Текст призыва к звонку"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Текст призыва к звонку",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text_ru",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Текст призыва к звонку",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text_uk",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Текст призыва к звонку",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Текст скидки"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Текст скидки"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Текст скидки"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text_uk",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Текст скидки"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text_uk",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_1_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Код телефона 1"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_1_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Номер телефона 1"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_2_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Код телефона 2"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_2_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Номер телефона 2"
            ),
        ),
    ]
