# Generated by Django 6.0.1 on 2026-02-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_sitesettings_call_text_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedialink",
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text",
            field=models.CharField(
                default="Заказать звонок", max_length=100, verbose_name="Текст звонка"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text_en",
            field=models.CharField(
                default="Заказать звонок",
                max_length=100,
                null=True,
                verbose_name="Текст звонка",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text_ru",
            field=models.CharField(
                default="Заказать звонок",
                max_length=100,
                null=True,
                verbose_name="Текст звонка",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="call_text_uk",
            field=models.CharField(
                default="Заказать звонок",
                max_length=100,
                null=True,
                verbose_name="Текст звонка",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text",
            field=models.CharField(
                default="Скидка -10% на первый заказ",
                max_length=255,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text_en",
            field=models.CharField(
                default="Скидка -10% на первый заказ",
                max_length=255,
                null=True,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text_ru",
            field=models.CharField(
                default="Скидка -10% на первый заказ",
                max_length=255,
                null=True,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discount_text_uk",
            field=models.CharField(
                default="Скидка -10% на первый заказ",
                max_length=255,
                null=True,
                verbose_name="Текст скидки",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text",
            field=models.CharField(
                default="Nuts", max_length=255, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text_en",
            field=models.CharField(
                default="Nuts", max_length=255, null=True, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text_ru",
            field=models.CharField(
                default="Nuts", max_length=255, null=True, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_text_uk",
            field=models.CharField(
                default="Nuts", max_length=255, null=True, verbose_name="Текст логотипа"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_1_code",
            field=models.CharField(
                default="+38 (067)", max_length=10, verbose_name="Код 1"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_1_number",
            field=models.CharField(
                default="555-55-55", max_length=20, verbose_name="Номер 1"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_2_code",
            field=models.CharField(
                default="+38 (063)", max_length=10, verbose_name="Код 2"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_2_number",
            field=models.CharField(
                default="333-33-33", max_length=20, verbose_name="Номер 2"
            ),
        ),
    ]
